packages:
  # 应用
  - 'apps/*'
  # 公共包
  - 'packages/*'
  - 'packages/configs/*'
  # 工程化脚本
  - 'scripts'
catalog:

catalogs:
  #web和server
  # 工程化相关依赖
  cli:
    '@types/css': ^0.0.38
    css: ^3.0.0
    prettier-plugin-ejs: ^1.0.3
    '@rollup/plugin-alias': ^5.1.1
    '@rollup/plugin-commonjs': ^28.0.6
    '@rollup/plugin-node-resolve': ^16.0.1
    '@rollup/plugin-typescript': ^12.1.4
    rollup: ^4.44.2
    rollup-plugin-delete: ^3.0.1
    rollup-plugin-dts: ^6.2.1
    lint-staged: ^16.1.2
    cz-customizable: ^7.4.0
    commitizen: ^4.3.1
    '@commitlint/config-conventional': ^19.8.1
    '@commitlint/cli': ^19.8.1
    prettier: ^3.5.3
    husky: ^9.1.7
    '@unocss/eslint-plugin': ^66.1.4
    'eslint': ^9.22.0
    'eslint-plugin-format': ^1.0.1
    '@antfu/eslint-config': ^4.13.3
    turbo: ^2.5.4
    typescript: ~5.8.0
    '@types/node': ^22.14.0
    axios: ^1.10.0
    crypto-js: ^4.2.0
    '@types/crypto-js': ^4.2.2
    dayjs: ^1.11.13
    uuid: ^11.1.0
  # api生产依赖
  api_prod:
    cookie-parser: ^1.4.7
    '@compodoc/compodoc': 1.1.25
    ejs: ^3.1.10
    nodemailer: ^7.0.3
    joi: ^17.13.3
    '@nest-lab/throttler-storage-redis': ^1.1.0
    ioredis: ^5.6.1
    '@nestjs-modules/mailer': ^2.0.2
    '@nestjs/event-emitter': ^3.0.1
    '@nestjs/jwt': ^10.2.0
    'passport-jwt': ^4.0.1
    '@nestjs/axios': ^4.0.0
    '@nestjs/throttler': ^6.4.0
    'svg-captcha': ^1.4.0
    pm2: ^6.0.8
    typeorm: 0.3.20
    rxjs: ^7.8.1
    reflect-metadata: ^0.2.2
    passport: ^0.7.0
    'passport-local': ^1.0.0
    '@nestjs/bullmq': ^11.0.2
    '@nestjs/cache-manager': ^2.3.0
    '@nestjs/common': ^10.4.19
    '@nestjs/config': ^4.0.2
    '@nestjs/core': ^10.4.19
    '@nestjs/mapped-types': ^2.1.0
    '@nestjs/passport': ^11.0.5
    '@nestjs/platform-express': ^10.4.19
    '@nestjs/swagger': ^8.1.1
    '@nestjs/typeorm': ^10.0.2
    mysql2: ^3.14.1
    etag: ^1.8.1
    cross-env: ^7.0.3
    class-validator: ^0.14.1
    class-transformer: ^0.5.1
    bullmq: ^5.54.0
    cache-manager: ^5.7.6
  # api开发依赖
  api_dev:
    '@types/cookie-parser': ^1.4.9
    copy-webpack-plugin: ^13.0.0
    webpack-bundle-analyzer: ^4.10.2
    '@types/ejs': ^3.1.5
    '@types/nodemailer': ^6.4.17
    '@types/passport-jwt': ^4.0.1
    run-script-webpack-plugin: ^0.2.3
    webpack: ^5.99.9
    webpack-node-externals: ^3.0.0
    nestjs-spelunker: ^1.3.2
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    jest: ^29.7.0
    ts-jest: ^29.4.0
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    globals: ^16.0.0
    '@types/jest': ^29.5.14
    '@types/passport-local': ^1.0.38
    '@types/etag': ^1.8.4
    '@types/express': ^5.0.0
    '@types/supertest': ^6.0.2
    '@nestjs/cli': ^10.4.9
    '@nestjs/schematics': ^10.2.3
    '@nestjs/testing': ^10.4.19
  # web生产依赖
  web_prod:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    vue-i18n: ^11.1.11
    '@vueuse/core': ^13.5.0
    '@iconify/vue': ^5.0.0
    '@iconify-json/icon-park': ^1.2.2
    element-plus: ^2.9.11
    nprogress: ^0.2.0
    vue: ^3.5.13
    vue-router: ^4.5.0
    pinia: ^3.0.1
    '@unocss/reset': ^66.1.4
  # web开发依赖
  web_dev:
    '@unocss/preset-icons': ^66.3.3
    vite-plugin-compression: ^0.5.1
    vite-plugin-imagemin: ^0.6.1
    vite-plugin-html: ^3.2.2
    '@tsconfig/node22': ^22.0.1
    '@types/nprogress': ^0.2.3
    '@unocss/preset-attributify': ^66.1.4
    '@vitejs/plugin-vue': ^5.2.3
    '@vitejs/plugin-vue-jsx': ^4.1.2
    '@vue/tsconfig': ^0.7.0
    autoprefixer: ^10.4.21
    postcss: ^8.5.4
    rollup-plugin-visualizer: ^6.0.3
    unocss: ^66.1.4
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    vite: ^6.2.4
    vite-plugin-vue-devtools: ^7.7.2
    npm-run-all2: ^7.0.2
    vue-tsc: ^2.2.8
