/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptchaImg: typeof import('./../pages/Login/components/CaptchaImg/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPickerPanel: typeof import('element-plus/es')['ElColorPickerPanel']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LoginProblem: typeof import('./../pages/Login/components/LoginProblem/index.vue')['default']
    MAside: typeof import('./../layouts/components/MAside/index.vue')['default']
    MBanner: typeof import('./../layouts/components/MBanner/index.vue')['default']
    MButton: typeof import('./../components/MButton/index.vue')['default']
    MCard: typeof import('./../layouts/components/MCard/index.vue')['default']
    MForm: typeof import('./../components/MForm/index.vue')['default']
    MI18nBtn: typeof import('./../components/MI18nBtn/index.vue')['default']
    MLoading: typeof import('./../components/MLoading/index.vue')['default']
    MMenu: typeof import('./../layouts/components/MMenu/index.vue')['default']
    MModeBtn: typeof import('./../components/MModeBtn/index.vue')['default']
    MThemeBtn: typeof import('./../components/MThemeBtn/index.vue')['default']
    MVideo: typeof import('./../components/MVideo/index.vue')['default']
    OtherLogin: typeof import('./../pages/Login/components/OtherLogin/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
