export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [0],
    'type-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'init',
        'feat',
        'fix',
        'merge',
        'impr',
        'perf',
        'docs',
        'refactor',
        'test',
        'cache',
        'delete',
        'move',
        'release',
        'deploy',
        'config',
        'upgrade',
        'downgrade',
        'style',
        'build',
        'script',
        'chore',
        'sync',
        'revert',
      ],
    ],
  },
}
